---
label: default
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: default
- name: loc
  type: text
  default: top
pages:
- content/test.md
